### ISSUE TITLE
Save File is not available

### ISSUE THREAD

**Issue by 4436tracker** [MrIkso/ArscEditor#1]
The Save File button is still not available after the file has been modified.TableChangedListener was not triggered.

**Comment by MrIkso** [comment]
Some error  have occurred while changing values? There shouldn't be any other problems why the TableChangedListener didn't work.

**Comment by KiGamji** [comment]
> The Save File button is still not available after the file has been modified.TableChangedListener was not triggered.

Same problem

**Comment by KiGamji** [comment]
> Some error have occurred while changing values? There shouldn't be any other problems why the TableChangedListener didn't work.

I have no errors, but save file button dont work
![image](https://user-images.githubusercontent.com/59279014/139962595-ea837d8e-50ba-42c0-b746-edbe67b0d70e.png)

**Comment by stevenjoezhang** [comment]
I tried to right click on the ID column, then edit the value in the pop-up window. The Save File button is working as expected.

However, double click the value in the Value column then edit it, the new value will not be saved. Maybe the Name and Value column should be read-only.

<img width="1012" alt="截屏2022-03-12 下午8 08 44" src="https://user-images.githubusercontent.com/16272760/158017377-f463242f-4302-4efb-86fd-5c3b4035221a.png">

**Comment by MrIkso** [comment]
> Maybe the Name and Value column should be read-only.

Yes, this filed read-only
