### ISSUE TITLE
Sir any usage of this library ☺️

### ISSUE THREAD

**Issue by developer-krushna** [MrIkso/ArscEditor#3]
Thanks for your reply 🙏

**Comment by MrIkso** [comment]
It's for pc. See source code

**Comment by developer-krushna** [comment]
> It's for pc. See source code

But sir i can convert it to Android platform like MT Manager...but in MT Manager it's paid for normal user

**Comment by developer-krushna** [comment]
> It's for pc. See source code

Just explain me how this works in PC sir,.Just by a sample code..Thanks ❤️

**Comment by developer-krushna** [comment]
> It's for pc. See source code

Sir what happened sir..
