### ISSUE TITLE
get string by resources

### ISSUE THREAD

**Issue by timscriptov** [MrIkso/ArscEditor#5]
Hi, can you tell me what lightweight tool would be suitable for this task? ArscBlamer is outdated, Pxb doesn't work either

```kotlin
fun getStringByResources(arsc: File, resId: Int) : String? {}
```

**Comment by MrIkso** [comment]
See [this](https://github.com/REAndroid/ARSCLib) lib, it a support new android 14/15 resources, [here](https://github.com/REAndroid/APKEditor/tree/master/src/main/java/com/reandroid/apkeditor) more examples
