### ISSUE TITLE
Can I add new resources or delete some unwanted resources?

### ISSUE THREAD

**Issue by xiaotujinbnb** [MrIkso/ArscEditor#6]
Can I add new resources or delete some unwanted resources?

**Comment by MrIkso** [comment]
Hi, don't can, it don't supported ArscBlamer, only view and edit existing resources. You might see  [this](https://github.com/REAndroid/ARSCLib) lib, it a support new android 14/15 resources and create/edit resources, [here](https://github.com/REAndroid/APKEditor) project with powerfull features
