### ISSUE TITLE
一个关于保存的事情

### ISSUE THREAD

**Issue by yingshadow12** [MrIkso/ArscEditor#7]
在编辑时请选择左边的ID，右键再弹出来的窗口中编辑
否着保存按钮将无法保存
如你已经直接双击Name和Value列修改，你还有补救的办法，请和正常编辑一样的办法，打开编辑窗口点击"OK"，将所有编辑过的数据经行一遍，如有没保存的将失去编辑过的数据

不知道是不是BUG
我的JAVA"zulu17.52.17-ca-jdk17.0.12-win_x64.msi"

**Comment by MrIkso** [comment]
Yes, you must edit value on dialog. It's a related to #1 issue. Maybe on future i improve logic for showing edit dialog

**Comment by MrIkso** [comment]
@yingshadow12 try new 1.0.4 version, curently edit dialog opened on any table item by right mouse button clicked
